### ISSUE TITLE
Unsupported uint8_type error with int8 models

### ISSUE THREAD

**Issue by gyulaz-htec** [migraphx-benchmark/AMDMIGraphX#165]
The error: `miopen make_tensor: MAKE_TENSOR: unsupported type uint8_type`
Issue comes from int8 models
Affected ONNX Zoo models are listed here: https://github.com/gyulaz-htec/models/blob/migraphx_testing/MIGRAPHX_fp32-int8.md

Repro step with migraphx:
`/code/AMDMIGraphX/build/bin/migraphx-driver run vision/classification/resnet/model/resnet50-v1-12-int8.onnx`

**Comment by nives-vukovic** [comment]
The error: miopen make_tensor: MAKE_TENSOR: unsupported type uint8_type in resnet50-v1-12-int8.onnx occurs in miopen_pooling::compute function in src/targets/gpu/pooling.cpp where make_tensor is called, which does not support shape::uint8_type and throws an error (rc/targets/gpu/include/migraphx/gpu/miopen.hpp).

**Comment by attila-dusnoki-htec** [comment]
Maybe we could make int8 from uint8 by shifting it? Casting it would truncate half the data.
Ted already did something similar (probably?) with zero points for int8 support in parsing.

**Comment by nives-vukovic** [comment]
The error is resolved when pooling is added to the list of operations that do not support unit8 type. Following 11 models were affected by this fix: 

- Image classification: [bvlcalexnet-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/classification/alexnet/model/bvlcalexnet-12-int8.tar.gz), [caffenet-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/classification/caffenet/model/caffenet-12-int8.tar.gz), [googlenet-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/classification/inception_and_googlenet/googlenet/model/googlenet-12-int8.tar.gz), [inception-v1-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/classification/inception_and_googlenet/inception_v1/model/inception-v1-12-int8.tar.gz), [resnet50-v1-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/classification/resnet/model/resnet50-v1-12-int8.tar.gz), [squeezenet1.0-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/classification/squeezenet/model/squeezenet1.0-12-int8.tar.gz), [vgg16-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/classification/vgg/model/vgg16-12-int8.tar.gz), [zfnet512-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/classification/zfnet-512/model/zfnet512-12-int8.tar.gz)
- Object Detection & Image Segmentation: [ResNet101-DUC-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/object_detection_segmentation/duc/model/ResNet101-DUC-12-int8.tar.gz), [fcn-resnet50-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/object_detection_segmentation/fcn/model/fcn-resnet50-12-int8.tar.gz), [ssd-12-int8.onnx](https://github.com/gyulaz-htec/models/tree/migraphx_testing/vision/object_detection_segmentation/ssd/model/ssd-12-int8.tar.gz)

When verify is attempted for these model inaccuracy error is reported, which can be analyzed in a separate issue.

**Comment by TedThemistokleous** [comment]
@nives-vukovic  you'll need to add in a shift similar to what I did for changes to MatMulInteger #2903
