### ISSUE TITLE
Gather crash

### ISSUE THREAD

**Issue by attila-dusnoki-htec** [migraphx-benchmark/AMDMIGraphX#174]
The following models are crashing  on the gather operator:
* https://huggingface.co/FFusion/FFusionXL-BASE/blob/main/text_encoder_2/model.onnx
* https://huggingface.co/aegon-h/sdxl/blob/main/text_encoder_2/model.onnx
* https://huggingface.co/softwareweaver/Sdxl-Turbo-Olive-Onnx/blob/main/text_encoder_2/model.onnx
* https://huggingface.co/softwareweaver/juggernaut-xl-v5-Olive-Onnx/blob/main/text_encoder_2/model.onnx
* https://huggingface.co/softwareweaver/stable-diffusion-xl-base-1.0-Olive-Onnx/blob/main/text_encoder_2/model.onnx
* https://huggingface.co/musiclang/musiclang-4k/blob/main/onnx/decoder_model_merged_quantized.onnx
The crash comes from this line:
https://github.com/ROCm/AMDMIGraphX/blob/b00489b383b931dcbd395ab316d5a6423e5b97ed/src/include/migraphx/op/gather.hpp#L133

Related MIGraphX issue: https://github.com/ROCm/AMDMIGraphX/issues/2838

**Comment by gyulaz-htec** [comment]
These models requires the `--input-dim` and `--fill1` to be set:
* https://huggingface.co/FFusion/FFusionXL-BASE/blob/main/text_encoder_2/model.onnx
* https://huggingface.co/aegon-h/sdxl/blob/main/text_encoder_2/model.onnx
* https://huggingface.co/softwareweaver/Sdxl-Turbo-Olive-Onnx/blob/main/text_encoder_2/model.onnx
* https://huggingface.co/softwareweaver/juggernaut-xl-v5-Olive-Onnx/blob/main/text_encoder_2/model.onnx
* https://huggingface.co/softwareweaver/stable-diffusion-xl-base-1.0-Olive-Onnx/blob/main/text_encoder_2/model.onnx
with the following: `--input-dim @input_ids 1 77 --fill1 input_ids`
