### ISSUE TITLE
Reduce operators axes input parse error

### ISSUE THREAD

**Issue by mirza-halilcevic** [migraphx-benchmark/AMDMIGraphX#68]
Tests for ONNX opset 18 versions of reduce operators fail due to `axes` now being an input instead of an attribute.

**Comment by mirza-halilcevic** [comment]
Cases when the `axes` input values can be parsed from the graph are properly handled by MIGraphX. An `axes` input that can't be evaluated during parsing is not yet supported. The current code relies on `axes` values being known during parsing to compute the output shape correctly. With `axes` as an input the output shape has to be dynamic.

This applies to all operators where the output shape depends on the input values, like Slice and Squeeze. The ONNX backend tests for these are currently disabled.

**Comment by music-dino** [comment]
Parsing and reference implementation have been updated.
MIGraphX currently does not support GPU operators where the output shapes is dependent on runtime input. This capability will be added some time in the future as part of furthering dynamic shape support. Once this is enabled, the GPU operator can be updated.
