### ISSUE TITLE
CastLike operator is unsupported

### ISSUE THREAD

**Issue by mirza-halilcevic** [migraphx-benchmark/AMDMIGraphX#69]
The CastLike operator is currently unsupported in MIGraphX.

CastLike is present since ONNX opset version 15.

**Comment by music-dino** [comment]
We determined in communication with AMD that we should wait for their side to implement it

**Comment by attila-dusnoki-htec** [comment]
Failing tests:
- test_relu_expanded_ver18_cpu
- test_softplus_example_expanded_ver18_cpu
- test_softplus_expanded_ver18_cpu
- test_softsign_example_expanded_ver18_cpu
- test_softsign_expanded_ver18_cpu
- test_shrink_hard_expanded_ver18_cpu
- test_shrink_soft_expanded_ver18_cpu

`RuntimeError: /code/AMDMIGraphX/src/onnx/onnx_parser.cpp:417: parse_graph: Unknown operator: CastLike`

**Comment by attila-dusnoki-htec** [comment]
Related issue: https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/issues/2151
