### ISSUE TITLE
Pool dilations attribute

### ISSUE THREAD

**Issue by mirza-halilcevic** [migraphx-benchmark/AMDMIGraphX#70]
The `dilations` attribute has been added to the AveragePool operator since opset v19 and support needs to be added.

**Comment by mirza-halilcevic** [comment]
The `dilations` attribute has been present in the MaxPool operator since opset 10. However, support for it has yet to be added and tests for MaxPool that depend on the `dilations` attribute are currently excluded.

**Comment by mirza-halilcevic** [comment]
We added parsing support for the `dilations` attribute and modified the reference implementation accordingly. The GPU target implementation uses the [MIOpen pooling layer](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/pooling.html) which at the moment doesn't support dilations. Neither does [DNNL](https://oneapi-src.github.io/oneDNN/v1.3/dev_guide_pooling.html) in the CPU target implementation.

**Comment by attila-dusnoki-htec** [comment]
The latest version of the PR added the missing test and fixed the logic for calculating dilations.
As mentioned above, the GPU version (MIOpen) does not support dilations.
As a workaround, we will investigate solutions with separating padding and calculating the kernels with slice op.
