### ISSUE TITLE
ScatterElements unsupported reduction modes and duplicate index support

### ISSUE THREAD

**Issue by mirza-halilcevic** [migraphx-benchmark/AMDMIGraphX#73]
A `reduction` attribute has been added to ScatterElements and ScatterND since opset v16 and support needs to be added.

**Comment by attila-dusnoki-htec** [comment]
Failing tests:
- test_scatter_elements_with_reduction_max_cpu
- test_scatter_elements_with_reduction_min_cpu

`RuntimeError: /code/AMDMIGraphX/src/onnx/parse_scatter.cpp:54: parse: PARSE_SCATTER: unsupported reduction mode max/max`

**Comment by music-dino** [comment]
test_scatter_elements_with_duplicate_indices_cpu fails due to lack of duplicate index handling
